In [1]:
import torch

In [3]:
x = torch.rand((3,2), requires_grad = True)
x

tensor([[0.7032, 0.1606],
        [0.1069, 0.5533],
        [0.1693, 0.6530]], requires_grad=True)

In [4]:
y = torch.rand((3,2), requires_grad = True)
y

tensor([[0.1469, 0.6007],
        [0.2110, 0.6731],
        [0.0852, 0.4340]], requires_grad=True)

In [8]:
z = torch.sum(x + y)
z

tensor(4.4972, grad_fn=<SumBackward0>)

In [9]:
z.backward()
print(x.grad, y.grad)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


### 复杂的自动求导

In [10]:
t_1 = torch.rand((3,2), requires_grad=True)
t_2 = torch.rand((3,2), requires_grad=True)
t_sum = t_1 ** 2 + t_2 ** 3
t_sum

tensor([[1.2223, 0.7080],
        [0.0875, 0.1093],
        [0.3305, 0.2814]], grad_fn=<AddBackward0>)

In [12]:
print(t_1.is_leaf)

True


In [13]:
print(t_sum.is_leaf)

False


In [15]:
t_sum.grad_fn