In [1]:
import torch
import numpy as np
print(torch.__version__)

1.4.0


### Tensor

In [2]:
x = torch.rand(2,3) # 均匀分布中从[0,1]随机抽取
x

tensor([[0.9119, 0.4710, 0.1926],
        [0.8843, 0.3241, 0.2018]])

In [3]:
print(x.shape)
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [12]:
z = torch.tensor([0.5, 0.7])
y = torch.rand(2)
print(z)
print(z.shape)
print(y)
print(y.shape)

tensor([0.5000, 0.7000])
torch.Size([2])
tensor([0.8544, 0.8433])
torch.Size([2])


In [13]:
scalar = torch.tensor(0.5)
print(scalar)
print(scalar.item())
print(scalar.shape)

tensor(0.5000)
0.5
torch.Size([])


In [18]:
print("float类型:")
test_half = scalar.half()
test_float = scalar.float()
test_double = scalar.double()
print(test_half)
print(test_float)
print(test_double)

print("\nint类型:")
test_char = scalar.char()
test_byte = scalar.byte()
test_short = scalar.short()
test_int = scalar.int()
test_long = scalar.long()
print(test_char)
print(test_byte)
print(test_short)
print(test_int)
print(test_long)

float类型:
tensor(0.5000, dtype=torch.float16)
tensor(0.5000)
tensor(0.5000, dtype=torch.float64)

int类型:
tensor(0, dtype=torch.int8)
tensor(0, dtype=torch.uint8)
tensor(0, dtype=torch.int16)
tensor(0, dtype=torch.int32)
tensor(0)


### Tensor <=> ndarray(Numpy)

In [20]:
tensor_1 = torch.randn((2,3))  # 标准正态分布随机抽取，均值为0，方差为1
tensor_1_numpy = tensor_1.numpy()
print(tensor_1_numpy)

[[-0.73605144 -0.44794384 -0.4850102 ]
 [ 1.3601235  -0.17342414 -0.50238407]]


In [25]:
numpy_1 = np.array([1,2,3])
tensor_2 = torch.from_numpy(numpy_1)
print(tensor_2)

tensor([1, 2, 3])


### 设备间转换

In [26]:
cpu_a = torch.rand(2,3)
cpu_a.type()

'torch.FloatTensor'

In [28]:
# gpu_a = cpu_a.cuda()
# gpu_a.type()

In [29]:
# cpu_b = gpu_a.cpu()
# cpu_b.type()

In [32]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
tensor_device = cpu_a.to(device)
print(tensor_device.type())

cpu
torch.FloatTensor


### 常用方法

In [37]:
# 初始化
tensor_ones = torch.ones((3,3))
tensor_zeros = torch.zeros((3,3))
tensor_randn = torch.randn((3,3))
tensor_eye = torch.eye(3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [40]:
# 维度操作
print(tensor_randn)
tensor_max_values, tensor_max_index = torch.max(tensor_randn, dim=1)  # 返回两个参数
print(tensor_max_values, tensor_max_index)

tensor([[-1.5716, -0.0637,  1.0178],
        [ 1.9220,  0.1563,  1.9815],
        [-0.6233, -0.9562,  0.1019]])
tensor([1.0178, 1.9815, 0.1019]) tensor([2, 2, 2])


In [41]:
tensor_sum = torch.sum(tensor_randn, dim=1)
tensor_sum

tensor([-0.6175,  4.0598, -1.4776])

In [42]:
tensor_add = tensor_randn + tensor_ones
tensor_add

tensor([[-0.5716,  0.9363,  2.0178],
        [ 2.9220,  1.1563,  2.9815],
        [ 0.3767,  0.0438,  1.1019]])

In [44]:
tensor_add.add_(tensor_ones)  # 以_结尾的均会改变调用值
tensor_add

tensor([[0.4284, 1.9363, 3.0178],
        [3.9220, 2.1563, 3.9815],
        [1.3767, 1.0438, 2.1019]])